### ISSUE TITLE
Azure Open AI 

### ISSUE THREAD

**Issue by gordingin** [Farzad-R/LLM-Zero-to-Hundred#22]
Hey Farzad,

    Looks like more (or the older projects) all run on Azure Open AI. Running them with just the OPENAI generates errors. I think you said upgrade the code but that is over my head on what to do there. Can you give instructions on how to create a Azure based OpenAI account so we can get the other keys?

thx
Ralph

**Comment by Farzad-R** [comment]
Hi Ralph,

You are right my older projects are with AzureOpenAI but the truth is switching the code to OpenAI is more convenient than using Azure especially if you don't need Azure in General. The problem with using Azure and all other cloud providers is that when you open an account if you are not experienced and careful, they will keep charging you for all sorts of different services. My goal was to design industrial applications which is why I was using Azure in the beginning but then I switched to openAI. The other reason to avoid AzureOpenAI is that their models are always behind the OpenAI models in terms of updates and capabilities. So, frameworks like LangGraph still do not support AzureOpenAI models for many tasks (ex: agentic graphs).

However, if you insist on opening an account on Azure, it is pretty straightforward. But the challenge comes after you open an account, where you need to create a resource to be able to use the services and there is where you need to be careful with what you are adding to it

**Comment by gordingin** [comment]
Thanks
